### ISSUE TITLE
Feature Request: Filtering

### ISSUE THREAD

**Issue by axdotl** [ricoberger/rcloneui#4]
It would be great to have filter support.

## Idea

When working with `rclone` cli there are a lot of [global flags](https://rclone.org/flags/), some of them are very handy to filter on files (e.g. `--max-age`, `--min-age`, `--max-size`, `--min-size`). It would be great to have support for this as well.

## Concerns

As filtering requires to read all elements in a bucket/ directory this might be very slow for large directories.
Maybe `--max-depth` or `--max-duration` can help.

**Comment by ricoberger** [comment]
Hi @axdotl, in [v0.4.0](https://github.com/ricoberger/rcloneui/releases/tag/v0.4.0) it is possible to set the `--max-age`, `--min-age`, `--max-size` and `--min-size` flags.

`--max-depth` is always set to `1` so that only the current directory is filtered, which hopefully hasn't a negative impact for large directories.
